### ISSUE TITLE
Decide on how to log info

### ISSUE THREAD

**Issue by mgrauer** [DigitalSlideArchive/NCI-SEER-Pediatric-WSI-Pilot#38] opened 2020-08-25 16:05 UTC
Once the import and export are functioning, we should revisit how we want to formulate logs. This may change what metadata we collect and store.

**Comment by manthey** [comment] 2020-08-25 16:31
Is this just a duplicate of #35?

**Comment by mgrauer** [comment] 2020-08-25 18:10
maybe. i stole your language for the description of this issue from #20 . if you feel these are the same, feel free to close this one.

**Closed** 2020-09-10 17:47 UTC
